name: check_version_format_action_test

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: nowsprinting/check-version-format-action@master
      id: version
      with:
        prefix: v
    - name: Version tag only step
      run: echo Found valid version format in tag!
      if: steps.version.outputs.is_valid == 'true'
    - name: Stable version only step
      run: echo Found stable version in tag!
      if: steps.version.outputs.is_stable == 'true'

