name: stable_version_regex

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check semantic version format in tag
      id: semver
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)+$ ]]; then
          echo ::set-output name=is_stable::true
        fi

    - name: Stable version only step
      run: |
        echo This tag is be stable version
      if: steps.semver.outputs.is_stable == 'true'
